version: '2'
services:
    web:
        build: .
        ports:
            - "80:5000"
        volumes:
            - ./src:/root/app
        depends_on:
            - redis
    redis:
        image: redis